name: backend-Code Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest tests/ --junitxml=test-results.xml

      # Step 5: Archive test results
      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure tests pass before deployment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Deploy to server
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Save the SSH key to a file
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          
          # Sync files to the server
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -p 5726 -i ssh_key" ./ root@103.234.187.197:/home/www/b2b/ashu/backend/
          
          # Connect to the server, navigate to the directory, and run the command in the background
          ssh -o StrictHostKeyChecking=no -i ssh_key -p 5726 root@103.234.187.197 << 'EOF'
            cd /home/www/b2b/ashu/backend
            nohup python3 manage.py runserver 0.0.0.0:8099 > server.log 2>&1 &
          EOF

      # Step 3: Cleanup - Remove SSH key
      - name: Cleanup
        run: rm -f ssh_key
